name: Pages
on:
  push:
    branches:
    - main
    paths:
    - 'pyqtribbon/**'
    - 'docs/source/**'
    - '.github/workflows/pages.yaml'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Install the package
      run: |
        pip install .
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: docs/source
        requirements_path: docs/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
